<a href="https://colab.research.google.com/github/ashwinidaya/Classify_ICDPointcloud_pointnet/blob/main/hdf5fileRead.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install h5py

In [ ]:
pip install numpy

In [ ]:
import numpy as np
import h5py

# initializing a random numpy array
arr = np.random.randn(1000)

# creating a file
with h5py.File('test.h5', 'w') as f:
    dset = f.create_dataset("default", data = arr)

In [ ]:

# open the file as 'f'
with h5py.File('test.h5', 'r') as f:
    data = f['default']

    # get the minimum value
    print(min(data))

    # get the maximum value
    print(max(data))

    # get the values ranging from index 0 to 15
    print(data[:15])



-3.696943551017006
3.130271533194096
[ 1.43374359  0.39796961 -1.57623704  2.01115041 -0.7906969   1.09179504
  0.42793113  0.87242933 -0.36790451 -1.30515453  2.55333334  0.4306097
  0.38736755 -0.87933674  0.41310152]


In [ ]:
with h5py.File('test.h5', 'r') as f:
   data_set = f['default']
   data = data_set[:]
   #i=0
   #label=data_set[:]+i
   #i+=i
print("---------------------DATA-----------------------------------")
print(data)



---------------------DATA-----------------------------------
[ 1.43374359e+00  3.97969607e-01 -1.57623704e+00  2.01115041e+00
 -7.90696895e-01  1.09179504e+00  4.27931127e-01  8.72429329e-01
 -3.67904507e-01 -1.30515453e+00  2.55333334e+00  4.30609703e-01
  3.87367549e-01 -8.79336736e-01  4.13101521e-01 -1.97832888e+00
  2.20371404e+00  1.80959524e+00 -5.20390784e-01 -1.11276972e+00
  1.56238444e-01 -3.69694355e+00  1.89967868e-01  4.80332849e-01
 -5.13965676e-01  1.78568076e+00  4.91398101e-01 -1.07422077e-01
 -8.39947570e-01  5.86103882e-01  1.37199012e+00 -6.18243775e-01
 -4.78583763e-02 -7.37566663e-01 -2.66302681e-01 -1.58025514e+00
 -2.66775753e+00  4.98255405e-01 -2.02175896e-01 -1.99135440e-01
  1.14888493e-01  2.63520141e-01 -4.50061461e-01 -9.17310699e-01
  9.54051945e-01 -7.59942228e-01  3.31389378e-02  1.31007866e+00
  9.36119831e-01  6.82339899e-01  6.57927768e-01  1.65926073e+00
  3.94792361e-02  2.17156354e-01  7.21272054e-01 -8.30212745e-01
  2.88181121e-02  7.15183864e

In [ ]:
cd /content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/ply

/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/ply


In [ ]:
!pip install plyfile

In [ ]:
#ICD
import h5py
import numpy as np
from plyfile import PlyData, PlyElement

filenames = [line.rstrip() for line in open("/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/filelist", 'r')]






In [ ]:
#f = h5py.File("./hdf5_data/data_training.h5", 'w')
f = h5py.File("/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/hdf5_data/dataTry1.h5", 'w')

a_data = np.zeros((len(filenames), 2048, 3))
label = np.zeros((len(filenames), 2048), dtype = np.uint8)


In [ ]:
#label=np.random(2048)
for i in range(0, len(filenames)):
	plydata = PlyData.read("/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/ply/" + filenames[i] + ".ply")
	piddata = [line.rstrip() for line in open("/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/points_label/" + filenames[i] + ".seg", 'r')]
	for j in range(0, 2048):
		a_data[i, j] = [plydata['vertex']['x'][j], plydata['vertex']['y'][j], plydata['vertex']['z'][j]]
		label[i,j] = piddata[j]


data = f.create_dataset("data", data = a_data)
label = f.create_dataset("label", data = sum(label))

In [ ]:
h5_file = h5py.File('/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/hdf5_data/dataTry1.h5', 'r')
list(h5_file)

['data', 'label']

In [ ]:
with h5py.File('/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/hdf5_data/dataTry1.h5', 'r') as f:
   data_set = f['data']
   label = f['label']
   data = data_set[:10]
   #i=0
   label=label[:1000]
   #i+=i
print("---------------------DATA-----------------------------------")
print(data)
print("---------------------LABEL-----------------------------------")
print(label)


---------------------DATA-----------------------------------
[[[129.03199768   0.50799948  30.95357895]
  [129.03199768   0.          30.95357895]
  [128.52400208   0.          30.95357895]
  ...
  [149.60598755  93.97999573  30.95357895]
  [148.84399414  93.97999573  30.95357895]
  [148.08200073  92.96399689  30.95357895]]

 [[  0.          84.5819931   10.15999889]
  [126.74599457  84.5819931   10.15999889]
  [126.74599457  83.31199646  10.15999889]
  ...
  [100.0759964   64.00799561  30.48000145]
  [100.583992    64.00799561  30.48000145]
  [101.09199524  64.00799561  30.48000145]]

 [[  0.         157.22598267  17.15007973]
  [214.12197876 157.22598267  17.15007973]
  [120.9039917  156.71798706  17.15007973]
  ...
  [115.31599426 140.96998596  17.15007973]
  [115.56999207 140.96998596  51.4502449 ]
  [115.8239975  140.96998596  17.15007973]]

 ...

 [[  0.          99.05999756  42.42816162]
  [176.52999878  99.05999756  42.42816162]
  [  0.          98.29799652  42.42816162]
  ...


In [ ]:
with h5py.File('/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/pointnet/data/ply_data_test0.h5', 'r') as f:
   data_set = f['data']
   label = f['label']
   data = data_set[:10]
   #i=0
   label=label[:1000]
   #i+=i
print("---------------------DATA-----------------------------------")
print(data)
print("---------------------LABEL-----------------------------------")
print(label)

KeyError: ignored

In [ ]:
h5_file1 = h5py.File('/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/hdf5_data/data_testingLabel.h5', 'r')
f = h5_file1
print(f.items())
list(h5_file1)


ItemsViewHDF5(<HDF5 file "data_testingLabel.h5" (mode r)>)


['data', 'label']

In [ ]:
data_h5 = f['data'][...]
label_h5 = f['label'][...]
print (data_h5, label_h5)
h5_file.close()

[[[0.66768223 0.6586741  0.1788255  ... 0.855026   0.8942886  0.885677  ]
  [0.6877524  0.58075845 0.58847106 ... 0.5726019  0.869538   0.5265756 ]
  [0.2900722  0.7424559  0.32733834 ... 0.2065871  0.6486577  0.79960924]
  ...
  [0.28667465 0.6074477  0.3975719  ... 0.13496864 0.4996196  0.32453695]
  [0.34267575 0.16326706 0.03465787 ... 0.63857216 0.6056252  0.34924966]
  [0.8639937  0.92922676 0.8468622  ... 0.11420566 0.18629447 0.6485288 ]]

 [[0.9909897  0.18584973 0.04690898 ... 0.15840054 0.14769898 0.16317293]
  [0.6209564  0.35689095 0.93483007 ... 0.40717024 0.899529   0.30577   ]
  [0.48302403 0.52772874 0.26959184 ... 0.585187   0.7379908  0.5081036 ]
  ...
  [0.09072958 0.31328586 0.9747487  ... 0.8788161  0.25778657 0.9827518 ]
  [0.04230941 0.05624467 0.70390844 ... 0.17256308 0.29736087 0.19561064]
  [0.9969452  0.28376886 0.35965654 ... 0.25835496 0.87389964 0.3665413 ]]

 [[0.3583018  0.67897934 0.09864227 ... 0.64281625 0.09880751 0.97119534]
  [0.927496   0.887232

In [ ]:
h5_file1 = h5py.File('/content/drive/My Drive/Colab Notebooks/ICD_PointCloud/data/hdf5_data/data_testingLabel.h5', 'r')
f = h5_file1
print(f.items())
list(h5_file1)


ItemsViewHDF5(<HDF5 file "data_testingLabel.h5" (mode r)>)


['data', 'label']