<a href="https://colab.research.google.com/github/ashwinidaya/Classify_ICDPointcloud_pointnet/blob/main/icd__hdf5_labelGenerated1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!sudo apt-get install hdf5-tools hdfview

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-430
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  java-wrappers libhdf4-0 libjgraph-java libjhdf4-java libjhdf4-jni
  libjhdf5-java libjhdf5-jni libslf4j-java
Suggested packages:
  www-browser libhdf4-doc libhdf4-dev hdf4-tools libcommons-logging-java
  liblog4j1.2-java
The following NEW packages will be installed:
  hdf5-tools hdfview java-wrappers libhdf4-0 libjgraph-java libjhdf4-java
  libjhdf4-jni libjhdf5-java libjhdf5-jni libslf4j-java
0 upgraded, 10 newly installed, 0 to remove and 7 not upgraded.
Need to get 1,911 kB of archives.
After this operation, 5,235 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 hdf5-tools amd64 1.10.0-patch1+docs-4 [390 kB]
Get:2 http://archive.ubuntu.com/ubun

In [ ]:
!pip install plyfile

  Created wheel for plyfile: filename=plyfile-0.7.1-cp36-none-any.whl size=32827 sha256=ea087e71810cfc41add1468ccea8a5cca06d8122d5d867b4795cc38b24b13b61
  Stored in directory: /root/.cache/pip/wheels/d6/0d/bf/6d603d81b98604d2ecfd5e99d4ab7c9af664fd5285ab82bbb0
Successfully built plyfile


In [ ]:
!sudo apt-get install libhdf5-dev
!pip install h5py

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libhdf5-dev is already the newest version (1.10.0-patch1+docs-4).
The following package was automatically installed and is no longer required:
  libnvidia-common-430
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.


In [ ]:
!pip install numpy

In [ ]:
!pip install IPython

In [ ]:
ls

data/  sample_data/


In [ ]:
!pip install Path

In [ ]:
from plyfile import PlyData, PlyElement
import numpy as np
import os
import h5py

In [ ]:
!python write_hdf5.py

python3: can't open file 'write_hdf5.py': [Errno 2] No such file or directory


In [ ]:
cd /content

/content


In [ ]:
cd data

/content/data


In [ ]:
!python write_hdf5.py

In [ ]:
from plyfile import PlyData, PlyElement
import numpy as np
import os
import h5py
h5_file = h5py.File('/content/data/hdf5_data/data_trainingLabel1.h5', 'r')
f = h5_file
print(f.items())
data_h5 = f['data'][...]
label_h5 = f['pid'][...]
print ("data and labels of point cloud data-------->")
print ("<------------------------------------------>")
print (data_h5, label_h5)
h5_file.close()

ItemsViewHDF5(<HDF5 file "data_trainingLabel1.h5" (mode r)>)
data and labels of point cloud data-------->
<------------------------------------------>
[[[129.03199768   0.50799948  30.95357895]
  [129.03199768   0.          30.95357895]
  [128.52400208   0.          30.95357895]
  ...
  [149.60598755  93.97999573  30.95357895]
  [148.84399414  93.97999573  30.95357895]
  [148.08200073  92.96399689  30.95357895]]

 [[  0.          84.5819931   10.15999889]
  [126.74599457  84.5819931   10.15999889]
  [126.74599457  83.31199646  10.15999889]
  ...
  [100.0759964   64.00799561  30.48000145]
  [100.583992    64.00799561  30.48000145]
  [101.09199524  64.00799561  30.48000145]]

 [[  0.         157.22598267  17.15007973]
  [214.12197876 157.22598267  17.15007973]
  [120.9039917  156.71798706  17.15007973]
  ...
  [115.31599426 140.96998596  17.15007973]
  [115.56999207 140.96998596  51.4502449 ]
  [115.8239975  140.96998596  17.15007973]]

 ...

 [[  0.         110.74398804  19.38528061]
  

In [ ]:

f = h5py.File("/content/data/hdf5_data/data_trainingLabel1.h5")
list(f)

['data', 'pid']

In [ ]:
!python write_hdf5_data_label.py

In [ ]:
f = h5py.File("/content/data/hdf5_data/data_trainingLabel2.h5")
list(f)

['data', 'label']

In [ ]:
#modelnetdataset hdf5 file pointnet
h5_file1 = h5py.File('/content/data/hdf5_data/ply_data_test0.h5', 'r')
f1 = h5_file1
print(f1.items())
data_h5 = f1['data'][...]
label_h5 = f1['label'][...]
print (data_h5, label_h5)
h5_file1.close()



ItemsViewHDF5(<HDF5 file "ply_data_test0.h5" (mode r)>)
[[[ 7.23155811e-02  7.90050387e-01 -1.31832689e-01]
  [-4.31412429e-01 -6.81382954e-01 -2.11278662e-01]
  [ 4.14364249e-01 -4.39900279e-01 -1.89980879e-01]
  ...
  [ 3.04637730e-01 -1.46631151e-01 -3.26471590e-02]
  [ 2.59602308e-01 -8.76633584e-01 -1.25613883e-01]
  [ 2.72864729e-01  5.62073030e-02 -7.41542578e-02]]

 [[ 2.21597191e-04  4.10960346e-01  8.60561490e-01]
  [ 9.24113691e-02  9.90411919e-03  2.26811022e-01]
  [-1.88553140e-01 -4.25489545e-02  4.47571091e-02]
  ...
  [-3.09268236e-01 -3.78694274e-02 -1.07925452e-01]
  [ 1.56596541e-01 -2.03937069e-02 -1.64598152e-01]
  [ 1.15681954e-01 -1.36326566e-01 -1.13515623e-01]]

 [[ 3.91751118e-02  1.40630186e-01  7.11435497e-01]
  [-4.49606299e-01  8.48013721e-03 -4.49488103e-01]
  [ 5.63381433e-01 -3.98830138e-02 -6.69193923e-01]
  ...
  [ 1.70331642e-01  6.97731599e-02 -7.99020052e-01]
  [-1.85376450e-01  1.69642046e-02  9.05939266e-02]
  [ 1.98819935e-01  1.94997966e-01  5.

In [ ]:
f = h5py.File("/content/data/hdf5_data/ply_data_train1.h5")
list(f)

['data', 'faceId', 'label', 'normal']

In [ ]:
#plane detection chair table dataset
f = h5py.File("/content/data/hdf5_data/data_testing_planeDetectiondata.h5")
list(f)

['data', 'pid']

In [ ]:
#modelnetdataset hdf5 file plane detection chair and table data and label with list of array list
h5_file2 = h5py.File('/content/data/hdf5_data/data_testing_planeDetectiondata.h5', 'r')
f2 = h5_file2
print(f2.items())
data_h5 = f2['data'][...]
label_h5 = f2['pid'][...]
print (data_h5, label_h5)
h5_file2.close()


ItemsViewHDF5(<HDF5 file "data_testing_planeDetectiondata.h5" (mode r+)>)
[[[ 2.33469993e-01  2.02869996e-01 -2.20960006e-01]
  [-6.01399988e-02  2.06340000e-01  3.62000009e-03]
  [ 2.92340010e-01  1.96209997e-01 -1.16900001e-02]
  ...
  [-2.83380002e-01  2.06340000e-01 -3.99199985e-02]
  [ 1.80260003e-01 -1.09389998e-01 -2.34640002e-01]
  [-3.73499990e-02  2.05689996e-01  2.40199998e-01]]

 [[-1.79780006e-01 -9.71700028e-02  1.33420005e-01]
  [ 1.55959994e-01 -1.73859999e-01 -1.48599997e-01]
  [-1.64759994e-01  8.79599974e-02  1.84839994e-01]
  ...
  [-1.31709993e-01  2.09270000e-01  1.84839994e-01]
  [-7.91599974e-02 -6.12399988e-02 -8.93199965e-02]
  [ 1.15440004e-01 -6.22599982e-02  1.60540000e-01]]

 [[-1.28240004e-01  1.33640006e-01  2.64169991e-01]
  [-1.65999997e-02  1.43130004e-01 -2.84660012e-01]
  [ 2.98999995e-03  1.43130004e-01  6.39299974e-02]
  ...
  [ 1.86800007e-02  1.43130004e-01 -2.00299993e-02]
  [-1.00680001e-01  1.43130004e-01  1.66040003e-01]
  [-1.20099999e-01  

In [ ]:
!pip install numpy

In [ ]:
import h5py
import numpy
with h5py.File('/content/sample_data/data/hdf5_data/data_training.h5', 'r') as f:
   print(f)

In [ ]:
!pip3 install pyntcloud

In [ ]:
from pyntcloud import PyntCloud

In [ ]:
bharath = PyntCloud.from_file("/content/data/ply/b1.ply")

In [ ]:
bharath

In [ ]:
from pyntcloud import PyntCloud

cloud = PyntCloud.from_file("./ply/y1.ply")

cloud.points

In [ ]:
!pip install plyfile

In [ ]:
!pip install numpy

In [ ]:
from plyfile import PlyData, PlyElement
import numpy as np
import os

In [ ]:
pip install IPython

In [ ]:
plydata = PlyData.read('/content/data/ply/b1.ply')
plydata

In [ ]:
plydata = PlyData.read("/content/data/ply/b1.ply")
data = np.asarray(plydata['vertex'][:])
print(data)

In [ ]:
for d in plydata["vertex"][:]:

  print(plydata['vertex'][:])

In [ ]:
pip install Path

In [ ]:
!sudo apt-get install libhdf5-dev
!pip install h5py

In [ ]:
import h5py

In [ ]:
f = h5py.File('/content/data/hdf5_data/data_testing.h5', 'r')
f

In [ ]:
list(f)

In [ ]:
#icd dataset hdf5 file data with label:IMPORTANT
h5_file = h5py.File('/content/data/hdf5_data/data_testing.h5', 'r')
f = h5_file
print(f.items())
data_h5 = f['data'][...]
label_h5 = f['pid'][...]
print (data_h5, label_h5)
h5_file.close()

In [ ]:
#modelnet40 dataset hdf5 file data with label:IMPORTANT
h5_file = h5py.File('/content/data/hdf5_data/ply_data_train1.h5', 'r')
f = h5_file
print(f.items())
data_h5 = f['data'][...]
label_h5 = f['label'][...]
print (data_h5, label_h5)
h5_file.close()

In [ ]:
#icd dataset hdf5 file data with label same as modelnet40 dataset:IMPORTANT
h5_file = h5py.File('/content/data/hdf5_data/data_testing.h5', 'r')
f = h5_file
print(f.items())


In [ ]:
data_h5 = f['data'][...]
label_h5 = sum(f['pid'][...])
print (data_h5, label_h5)
h5_file.close()

In [ ]:
ls

In [ ]:
cd ./

In [ ]:
ls

In [ ]:
cd ../

In [ ]:
ls

In [ ]:
!python write_hdf5.py

In [ ]:
#ICD dataset hdf5 file data with label:IMPORTANT------->label single value----> [3 7 6 ... 4 8 6]

h5_file = h5py.File('/content/data/hdf5_data/data_trainingLabel.h5', 'r')
f = h5_file
print(f.items())
data_h5 = f['data'][...]
label_h5 = f['pid'][...]
print ("data and labels of point cloud data-------->")
print ("<------------------------------------------>")
print (data_h5, label_h5)
h5_file.close()

In [ ]:
#write_hdf5.py
import h5py
import numpy as np
from plyfile import PlyData, PlyElement

filenames = [line.rstrip() for line in open("filelist", 'r')]

#f = h5py.File("./hdf5_data/data_training.h5", 'w')
f = h5py.File("/content/data/hdf5_data/data_trainingLabel.h5", 'w')

a_data = np.zeros((len(filenames), 2048, 3))
a_pid = np.zeros((len(filenames), 2048), dtype = np.uint8)

for i in range(0, len(filenames)):
	plydata = PlyData.read("/content/data/ply/" + filenames[i] + ".ply")
	piddata = [line.rstrip() for line in open("/content/data/points_label/" + filenames[i] + ".seg", 'r')]
	for j in range(0, 2048):
		a_data[i, j] = [plydata['vertex']['x'][j], plydata['vertex']['y'][j], plydata['vertex']['z'][j]]
		a_pid[i,j] = piddata[j]

data = f.create_dataset("data", data = a_data)
pid = f.create_dataset("pid", data = sum(a_pid))


In [ ]:
#Only label printed
#ICD dataset hdf5 file data with label:IMPORTANT------->label single value----> [3 7 6 ... 4 8 6]

h5_file = h5py.File('/content/data/hdf5_data/data_trainingLabel.h5', 'r')
f = h5_file
print(f.items())
#data_h5 = f['data'][...]
label_h5 = f['pid'][...]
print ("labels of point cloud data-------->")
print(label_h5)
h5_file.close()